spring:
  application:
    name: tickets
  datasource:
    url: jdbc:h2:mem:ticketsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  flyway:
    clean-disabled: false
    locations: classpath:db/migration,classpath:db/testdata